// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCefNeaUq5jT1l9cwPly_Bfu8HNJ111GJU',
    appId: '1:89127608833:web:8b5a72ae15f66bdb415600',
    messagingSenderId: '89127608833',
    projectId: 'gymmanagementapp-889b3',
    authDomain: 'gymmanagementapp-889b3.firebaseapp.com',
    storageBucket: 'gymmanagementapp-889b3.firebasestorage.app',
    measurementId: 'G-8HJSXFWX8S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJZQBTLdih5gb9aBqT2Ojh5IVMya8nP-c',
    appId: '1:89127608833:android:c0eff7b95fe8d92d415600',
    messagingSenderId: '89127608833',
    projectId: 'gymmanagementapp-889b3',
    storageBucket: 'gymmanagementapp-889b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGyRLee4wDfkxqfTylkrkzz1DW59p4Jhk',
    appId: '1:89127608833:ios:740b08863865223b415600',
    messagingSenderId: '89127608833',
    projectId: 'gymmanagementapp-889b3',
    storageBucket: 'gymmanagementapp-889b3.firebasestorage.app',
    iosBundleId: 'com.example.gymManagementApp',
  );
}
